apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-deployment
  labels:
    app: account
spec:
  replicas: 2
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
      - name: account
        image: samrituab/accountservice_web-app:latest
        ports:
        - containerPort: 8082
        env:
          - name: MONGO_DB
            valueFrom:
              configMapKeyRef:
                name: microservices-config
                key: account-db
          - name: MONGO_HOST
            valueFrom:
              configMapKeyRef:
                name: microservices-config
                key: car-rental-mongodb
          - name: MONGO_PW
            valueFrom:
              secretKeyRef:
                name: microservices-secrets
                key: mongodb-password
          - name: MONGO_USER
            valueFrom:
              secretKeyRef:
                name: microservices-secrets
                key: mongodb-username
          - name: JWT-SECRET
            valueFrom:
              secretKeyRef:
                name: microservices-secrets
                key: jwt-secret
          - name: USER-SERVICE-AUTH
            valueFrom:
              secretKeyRef:
                name: microservices-secrets
                key: user-service-auth
          - name: KAFKA-SERVICE
            valueFrom:
              configMapKeyRef:
                name: microservices-config
                key: kafka-service
          - name: USER-SERVICE-URL
            valueFrom:
              configMapKeyRef:
                name: microservices-config
                key: user-service-url

---

apiVersion: v1
kind: Service
metadata:
  name: account-service
spec:
  type: LoadBalancer
  selector:
    app: account
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082
status:
  loadBalancer: {}