apiVersion: v1
kind: ConfigMap
metadata:
  name: microservices-config
data:
  car-rental-mongodb: car-rental-mongodb.default.svc.cluster.local
  reservation-db: reservation-db
  car-db: car-db
  review-db: review-db
  inventory-db: inventory-db
  account-db: account-db
  user-db: user-db
  kafka-service: kafka-broker-0.kafka-broker-headless.default.svc.cluster.local
  kafka-consumer: kafka-broker.default.svc.cluster.local
  JWT_EXPIRATION_MS : "86400000"
  inventory-service-url : inventory-service.default.svc.cluster.local:8085
  user-service-url : user-service.default.svc.cluster.local:8081
  car-service-url : car-service.default.svc.cluster.local:8083
  payment-service-url : payment-service.default.svc.cluster.local:8087
