apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-deployment
  labels:
    app: review
spec:
  replicas: 2
  selector:
    matchLabels:
      app: review
  template:
    metadata:
      labels:
        app: review
    spec:
      containers:
      - name: review
        image: filmon143/reviewservice_web-app:latest
        ports:
        - containerPort: 8084
        env:
          - name: MONGO_DB
            valueFrom:
              configMapKeyRef:
                name: microservices-config
                key: review-db
          - name: MONGO_HOST
            valueFrom:
              configMapKeyRef:
                name: microservices-config
                key: car-rental-mongodb
          - name: MONGO_PW
            valueFrom:
              secretKeyRef:
                name: microservices-secrets
                key: mongodb-password
          - name: MONGO_USER
            valueFrom:
              secretKeyRef:
                name: microservices-secrets
                key: mongodb-username
          - name: JWT-SECRET
            valueFrom:
              secretKeyRef:
                name: microservices-secrets
                key: jwt-secret
          - name: KAFKA-SERVICE
            valueFrom:
              configMapKeyRef:
                name: microservices-config
                key: kafka-service

---

apiVersion: v1
kind: Service
metadata:
  name: review-service
spec:
  type: LoadBalancer
  selector:
    app: review
  ports:
  - protocol: TCP
    port: 8084
    targetPort: 8084
status:
  loadBalancer: {}